// <auto-generated />
using HoneyCosmetics.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HoneyCosmetics.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520120000_AddCouponOneTimePerUser")]
    partial class AddCouponOneTimePerUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
